package com.godeltech.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.List;

@DynamoDBTable(tableName = "album")
public class Album {

    @Id
    @DynamoDBIgnore
    @JsonIgnore
    private AlbumId albumId;
    private String artist;
    private List<Song> songs;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return albumId == null ? null : albumId.getId();
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return albumId == null ? null : albumId.getName();
    }

    @DynamoDBAttribute(attributeName = "artist")
    public String getArtist() {
        return artist;
    }

    @DynamoDBAttribute(attributeName = "songs")
    public List<Song> getSongs() {
        return songs;
    }



    public void setId(String id) {
        if (albumId == null) {
            albumId = new AlbumId();
        }
        albumId.setId(id);
    }

    public void setName(String name) {
        if (albumId == null) {
            albumId = new AlbumId();
        }
        albumId.setName(name);
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }
}
