package com.godeltech.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.springframework.data.annotation.Id;

import java.util.List;

@JsonPropertyOrder(value = {"title",
        "artist",
        "price",
        "genre",
        "songs"})
@DynamoDBTable(tableName = "album")
public class Album {

    @Id
    @JsonIgnore
    private AlbumId albumId;
    private double price;
    private String genre;
    private List<Song> songs;


    @DynamoDBHashKey(attributeName = "artist")
    @DynamoDBAutoGeneratedKey
    public String getArtist() {
        return albumId == null ? null : albumId.getArtist();
    }

    @DynamoDBRangeKey(attributeName = "title")
    public String getTitle() {
        return albumId == null ? null : albumId.getTitle();
    }

    @DynamoDBAttribute(attributeName = "price")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "GenrePriceIndex")
    public double getPrice() {
        return price;
    }

    @DynamoDBAttribute(attributeName = "genre")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "GenrePriceIndex")
    public String getGenre() {
        return genre;
    }

    @DynamoDBAttribute(attributeName = "songs")
    public List<Song> getSongs() {
        return songs;
    }

    public void setArtist(String artist) {
        if (albumId == null) {
            albumId = new AlbumId();
        }
        albumId.setArtist(artist);
    }

    public void setTitle(String title) {
        if (albumId == null) {
            albumId = new AlbumId();
        }
        albumId.setTitle(title);
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }
}
