package com.godeltech.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.*;

import java.io.Serializable;

@Builder
@NoArgsConstructor
@Getter
@Setter
@AllArgsConstructor
public class AlbumId{

    @DynamoDBHashKey(attributeName = "artist")
    @DynamoDBAutoGeneratedKey
    private String artist;
    @DynamoDBRangeKey(attributeName = "title")
    private String title;

}
